---
title: "2022-05-18_MutationalData_MAFtools"
author: "Joe"
date: "5/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load Packages
```{r}
library('xlsx')
library(dplyr)
library(ggplot2)
library(ggpubr)
library(DESeq2)
library(ggrepel)
library(msigdbr)
library(data.table)
library("DT")
library(pheatmap)
library(maftools)
```

##Load Data
```{r}
mafDir <- "~/OneDrive - Johns Hopkins/JHU_PDAC_Collaboration/MAF"
maffiles = (list.files(mafDir, recursive = TRUE,full.names = T))
maf_filenames = (list.files(mafDir, recursive = T,full.names = F))
maf_filenames = gsub(".maf","",maf_filenames)

##Load SampInfo
SampInfo=read.csv("SampInfo_tmb_fromMAF.csv", row.names=1)
SampInfo$Tumor_Sample_Barcode <- rownames(SampInfo)

##Create MAFobject
merged <- merge_mafs(maffiles, clinicalData=SampInfo)

##Save
saveRDS(merged, file="mergedMAF.rds")

##Rename all Tumor Sample Barcodes 
for (i in 1:length(levels(merged@data$Tumor_Sample_Barcode))){
  for (j in 1:nrow(SampInfo)){
  if (levels(merged@data$Tumor_Sample_Barcode)[i]==SampInfo$Tumor_Sample_Barcode[j]){ 
    levels(merged@data$Tumor_Sample_Barcode)[i] <- SampInfo$Publication_id[j]}
  if (levels(merged@variants.per.sample$Tumor_Sample_Barcode)[i]==SampInfo$Tumor_Sample_Barcode[j]){ 
    levels(merged@variants.per.sample$Tumor_Sample_Barcode)[i] <- SampInfo$Publication_id[j]}
  if (levels(merged@variant.type.summary$Tumor_Sample_Barcode)[i]==SampInfo$Tumor_Sample_Barcode[j]){ 
    levels(merged@variant.type.summary$Tumor_Sample_Barcode)[i] <- SampInfo$Publication_id[j]}
  if (levels(merged@variant.classification.summary$Tumor_Sample_Barcode)[i]==SampInfo$Tumor_Sample_Barcode[j]){ 
    levels(merged@variant.classification.summary$Tumor_Sample_Barcode)[i] <- SampInfo$Publication_id[j]}
  if (levels(merged@maf.silent$Tumor_Sample_Barcode)[i]==SampInfo$Tumor_Sample_Barcode[j]){ 
    levels(merged@maf.silent$Tumor_Sample_Barcode)[i] <- SampInfo$Publication_id[j]}
  }
}

##Change tumor sample barcodes in meta to be the Pub_ID
colnames(merged@clinical.data)[8] <- "PublishNames"
colnames(merged@clinical.data)[7] <- "Tumor_Sample_Barcode"
```


##TMB Results
```{r}
##Extract TMB -- capture size as per ECGC
tmb <- tmb(merged, captureSize = 35.8)
tmb_data <- as.data.frame(tmb)
rownames(tmb_data)<- tmb_data$Tumor_Sample_Barcode
tmb_data <- tmb_data[,-1]
##Save
write.csv(tmb_data, file = "tmb_fromMAF.csv")

##Correlate with prev. TMB results
tmb_data$fromLei <- c(20,27,46,81,91,82,100,93,81,134,120,96,136,123,131,159,173,201,189)
cor(tmb_data$total,tmb_data$fromLei)
##Checks out! == correlation of 0.9597991

##Merge TMB w/ SampInfo
colnames(tmb)[1] <- "Publication_id"
SampInfo <- merge(SampInfo,tmb, by="Publication_id")

##Boxplots of TMB by treatment and outcome
pdf(file="TMBBoxplot.pdf")
ggplot(SampInfo, aes(y=total_perMB,x=Treatment))+geom_boxplot()+geom_point(aes(color=Treatment,shape=OS)) + stat_compare_means(method="t.test")+ ggtitle("TMB boxplot total_perMB by Treatment")

ggplot(SampInfo, aes(y=total_perMB,x=OS))+geom_boxplot()+geom_point(aes(color=Treatment,shape=OS))+ stat_compare_means(method="t.test")+ ggtitle("TMB boxplot total_perMB by Outcome")

ggplot(SampInfo, aes(x=CD66b_Gr_Status, y=total_perMB)) + geom_boxplot() + geom_point(aes(col=Treatment,shape=OS)) + stat_compare_means(comparisons = list(c("High","Low")),method = "t.test") + ggtitle("TMB boxplot total_perMB by CD66b_Gr_Status")

ggplot(SampInfo, aes(x=Treg_Status, y=total_perMB)) + geom_boxplot() + geom_point(aes(col=Treatment,shape=OS)) + stat_compare_means(comparisons = list(c("High","Low")),method = "t.test") + ggtitle("TMB boxplot total_perMB by Treg_Status")

ggplot(SampInfo, aes(x=CD8_CD137_Status, y=total_perMB)) + geom_boxplot() + geom_point(aes(col=Treatment,shape=OS)) + stat_compare_means(comparisons = list(c("High","Low")),method = "t.test") + ggtitle("TMB boxplot total_perMB by CD8_CD137_Status")

ggplot(SampInfo, aes(x=M1_Status, y=total_perMB)) + geom_boxplot() + geom_point(aes(col=Treatment,shape=OS)) + stat_compare_means(comparisons = list(c("High","Low")),method = "t.test") + ggtitle("TMB boxplot total_perMB by M1_Status")

ggplot(SampInfo, aes(x=M2_Status, y=total_perMB)) + geom_boxplot() + geom_point(aes(col=Treatment,shape=OS)) + stat_compare_means(comparisons = list(c("High","Low")),method = "t.test") + ggtitle("TMB boxplot total_perMB by M2_Status")

ggplot(SampInfo, aes(x=IL17_Signaling_Status, y=total_perMB)) + geom_boxplot() + geom_point(aes(col=Treatment,shape=OS)) + stat_compare_means(comparisons = list(c("High","Low")),method = "t.test") + ggtitle("TMB boxplot total_perMB by IL17_Signaling_Status")

ggplot(SampInfo, aes(x=CD4_Th17_Status, y=total_perMB)) + geom_boxplot() + geom_point(aes(col=Treatment,shape=OS)) + stat_compare_means(comparisons = list(c("High","Low")),method = "t.test") + ggtitle("TMB boxplot total_perMB by CD4_Th17_Status")


dev.off()
```


##MAF Plots
```{r}
##MAF Summary
plotmafSummary(maf = merged, rmOutlier = TRUE, addStat = 'median', dashboard = T, titvRaw = FALSE, showBarcodes = T, textSize = .25)

##MAFSummary Barplot Setup -- from MAFsummary code
vcs = getSampleSummary(merged)
vcs = vcs[,colnames(vcs)[!colnames(x = vcs) %in% c('total', 'Amp', 'Del', 'CNV_total')], with = FALSE]
#order based on most events
vcs = vcs[,c(1,order(colSums(x = vcs[,2:(ncol(vcs)), with =FALSE]), decreasing = TRUE)+1), with =FALSE] 
#Make Dataframe
data.table::setDF(vcs)
rownames(x = vcs) = vcs$Tumor_Sample_Barcode
#Remove rownames column
vcs = vcs[,-1]
#order based on most events
vcs = vcs[order(rowSums(vcs),decreasing = T),] 
#Transpose
vcs = t(vcs)
#Vector of colors
col = c("green","blue","red","yellow","orange","purple","brown","pink","black")
#Add samplenames to color vector
names(col) = rownames(vcs)

#--------------------------- variant per sample plot -----------------

graphics::layout(mat = matrix(c(1, 1, 2, 2, 3, 3), nrow = 3, byrow = TRUE), heights = c(4, 4, 3))

par(mar = c(7, 2, 3, 1))
b = barplot(vcs, col = col[rownames(vcs)], border = NA, axes = FALSE, names.arg =  rep("", ncol(vcs)))
  axis(side = 1, at = b, labels = colnames(vcs), font = 2, cex.axis =.5 , las = 2, lwd = 1)
  legend("topright",fill = col,legend=names(col))
  abline(h=median(colSums(vcs)),lwd=2,lty=2,col="maroon")
  title("Variants per Sample")

#------ Top10 Mutations plot -------
  
oncoplot(merged, showTumorSampleBarcodes = T)

##Print Plots in PDF
pdf(file="MAFSummary.pdf", width = 15)

#Summary
plotmafSummary(maf = merged, rmOutlier = TRUE, addStat = 'median', dashboard = T, titvRaw = FALSE, showBarcodes = T, textSize = .25)

##Oncoplot
oncoplot(merged, showTumorSampleBarcodes = T, fontSize = 0.5, clinicalFeatures = c("Treatment","OS","CD66b_Gr_Status"), sortByAnnotation = T,removeNonMutated = F)

layout(matrix(1:1, nrow=1))
par(mar=c(6,1,3,1))

#Barplots
all = barplot(vcs, col = col[rownames(vcs)], border = NA, axes = FALSE, names.arg =  rep("", ncol(vcs)))
  axis(side = 1, at = b, labels = colnames(vcs), font = 2, cex.axis =.5 , las = 2, lwd = 1)
  legend("topright",fill = col,legend=names(col))
  abline(h=median(colSums(vcs)),lwd=2,lty=2,col="maroon")
  title(paste0("Variants per Sample -- Median = ", median(colSums(vcs))))

dev.off()

```